from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import joblib

# Preprocesamiento básico
def preprocesar_texto(texto):
    return texto.lower().strip()

# Frases por categoría 
frases_por_categoria = {
    "consulta": [
        "¿Cuál es el motivo de su visita?",
        "¿En qué puedo asistirlo hoy?",
        "¿Qué desea consultar conmigo?",
        "¿Qué problema de salud lo aqueja hoy?",
        "¿Por qué ha venido hoy?",
        "¿En qué aspecto necesita ayuda médica?",
        "¿Cuál es su motivo de consulta?",
        "¿Qué desea revisar hoy conmigo?",
        "¿Qué lo trae a esta consulta?",
        "¿Qué situación médica le preocupa?",
        "¿Qué síntoma quiere comentar?",
        "¿Qué le gustaría abordar en esta cita?",
        "¿Por qué decidió consultar hoy?",
        "¿Tiene alguna molestia reciente?",
        "¿Con qué puedo ayudarle hoy?",
        "¿Qué síntomas está presentando?",
        "¿Qué tema médico desea tratar?",
        "¿Hay algo en particular que lo incomoda?",
        "¿Qué inquietud médica tiene?",
        "¿Qué desea tratar el día de hoy?",
        "¿Hay algo que lo motivó a venir?",
        "¿Qué condición le preocupa?",
        "¿Viene por alguna molestia reciente?",
        "¿Qué lo motivó a hacer esta consulta?",
        "¿Vino por chequeo o por malestar?",
        "¿Tiene alguna duda médica que quiera resolver?",
        "¿Siente alguna molestia que deba atenderse?",
        "¿Por qué solicitó esta cita médica?",
        "¿Qué desea revisar conmigo hoy?",
        "¿Quiere hablar de algún síntoma en especial?",
        "¿Hay algo que esté afectando su salud?",
        "¿Le preocupa alguna condición médica específica?",
        "¿Tiene alguna dolencia de la cual quiera hablar?",
        "¿Qué quiere comunicar sobre su salud?",
        "¿Desea atención por algo en particular?",
        "¿Qué es lo que más le molesta últimamente?",
        "¿Tiene algo que quiera comentar médicamente?",
        "¿Está experimentando síntomas nuevos?",
        "¿Quiere contarme qué siente últimamente?",
        "¿Viene a consulta por algún motivo específico?",
        "¿Podría explicarme qué lo trajo hoy aquí?",
        "¿Hay alguna urgencia médica?",
        "¿Busca orientación médica general?",
        "¿Tiene alguna patología conocida?",
        "¿Busca confirmar algún diagnóstico?",
        "¿Vino para hablar de un tratamiento?",
        "¿Qué le gustaría tratar en la consulta?",
        "¿Tiene dudas sobre su condición actual?",
        "¿Hay síntomas que se hayan agravado?",
        "¿Tiene algún seguimiento pendiente?",
        "¿Quiere descartar alguna enfermedad?",
        "¿Qué te trae por aquí hoy?",
        "¿En qué te puedo ayudar?",
        "Cuéntame qué es lo que te molesta.",
        "¿Qué te está preocupando últimamente?",
        "¿Qué problema de salud quieres revisar?",
        "¿Vienes por algún malestar en particular?",
        "¿Qué síntomas estás notando?",
        "¿Cómo te has estado sintiendo últimamente?",
        "¿Qué fue lo que te hizo decidir venir hoy?",
        "¿Te ha pasado esto antes o es la primera vez?",
        "¿Qué parte de tu cuerpo te está dando lata?",
        "¿Vienes por algo que empezó hoy o ya llevas días así?",
        "¿Hay algo que te preocupe en especial?",
        "¿Qué te gustaría que revisáramos primero?",
        "¿Has notado algún cambio en tu cuerpo últimamente?",
        "¿Qué te trae hoy por aquí?",
        "¿Qué te está molestando últimamente?",
        "¿Qué problema quieres revisar hoy?",
        "¿Qué fue lo que te hizo venir al consultorio?",
        "¿Cómo puedo ayudarte hoy?",
        "¿Qué síntomas te preocupan más?",
        "¿Qué molestias estás sintiendo?",
        "¿Qué te pasa últimamente?",
        "¿Vienes por algo en particular?",
        "¿Qué sientes hoy?",
        "¿Cuál es tu principal malestar?",
        "¿Qué problema de salud tienes hoy?",
        "¿Qué te ocurre desde hace unos días?",
        "¿Por qué decidiste venir a la consulta?",
        "¿Hay algo que te preocupe en tu salud?",
        "¿Qué molestias has notado últimamente?",
        "¿Qué malestar sientes?",
        "¿Vienes por alguna molestia en específico?",
        "¿Qué síntomas has tenido estos días?",
        "¿Qué ha cambiado en tu salud últimamente?",
        "¿Cuál es tu principal preocupación médica?",
        "¿Qué tipo de dolor o molestia tienes?",
        "¿Qué síntomas presentas ahora mismo?",
        "¿Por qué decidiste venir al médico hoy?",
        "¿Qué es lo que más te molesta ahora?"
    ],
    "frecuencia": [
        "¿Con qué frecuencia se presentan los síntomas?",
        "¿Cada cuánto tiempo ocurre el dolor?",
        "¿Esto sucede todos los días o solo a veces?",
        "¿Cuántas veces por semana siente molestias?",
        "¿El malestar ocurre frecuentemente?",
        "¿Aparecen los síntomas más de una vez al mes?",
        "¿Esto ocurre de forma constante?",
        "¿Tiene síntomas diarios?",
        "¿Es algo que ocurre semanalmente?",
        "¿El dolor es ocasional o frecuente?",
        "¿Los síntomas son esporádicos o regulares?",
        "¿Esto ocurre una vez por día o menos?",
        "¿Suele presentarse cada semana?",
        "¿Con qué regularidad siente esto?",
        "¿Experimenta el dolor de manera repetitiva?",
        "¿Es una molestia que viene y va?",
        "¿Se repite a menudo?",
        "¿Cuántas veces al mes lo siente?",
        "¿Esto pasa con frecuencia?",
        "¿El dolor ocurre cada cierto tiempo?",
        "¿Vuelve el malestar varias veces?",
        "¿Es una situación recurrente?",
        "¿Esto le sucede constantemente?",
        "¿Padece esto más de una vez por semana?",
        "¿Es común que aparezcan estos síntomas?",
        "¿Ocurre en ciertos días del mes?",
        "¿Esto pasa habitualmente?",
        "¿Es un problema que se presenta seguido?",
        "¿El dolor aparece a diario?",
        "¿Es una molestia constante?",
        "¿El síntoma se presenta sin falta cada semana?",
        "¿Cada cuánto nota el malestar?",
        "¿Esto le sucede cada dos días?",
        "¿Con qué periodicidad aparece el dolor?",
        "¿Es frecuente esta condición?",
        "¿La molestia ocurre con regularidad?",
        "¿Esto se manifiesta muchas veces?",
        "¿Con qué continuidad le sucede?",
        "¿Se le repite el síntoma durante la semana?",
        "¿Le ha pasado muchas veces últimamente?",
        "¿Los episodios son continuos?",
        "¿Esto sucede un par de veces a la semana?",
        "¿Esto ha sido muy seguido últimamente?",
        "¿Ha notado una frecuencia alta de episodios?",
        "¿Esto le ocurre de forma muy seguida?",
        "¿Le pasa varias veces por mes?",
        "¿Esto le sucede constantemente desde hace tiempo?",
        "¿Esto se ha vuelto común?",
        "¿Tiene episodios reiterativos?",
        "¿Lo siente muchas veces al mes?",
        "¿Este síntoma es persistente?",
        "¿Esto te pasa todos los días o solo a veces?",
        "¿Cada cuánto te viene ese dolor?",
        "¿Sucede una vez al día, más seguido o menos?",
        "¿Te pasa seguido o es muy ocasional?",
        "¿Lo sientes varias veces por semana?",
        "¿Te ha pasado muchas veces últimamente?",
        "¿Es algo que viene y va o se queda por mucho tiempo?",
        "¿Hace cuánto fue la última vez que lo sentiste?",
        "¿Ha aumentado la frecuencia últimamente?",
        "¿Cada vez es más común o sigue igual?",
        "¿Cuántas veces al día te sucede esto?",
        "¿Te pasa a ciertas horas o es aleatorio?",
        "¿Solo ocurre por las noches o también en el día?",
        "¿Lo sientes más cuando haces algo en especial?",
        "¿Con qué regularidad te da ese malestar?",
        "¿Cada cuánto te ocurre eso?",
        "¿Te pasa todos los días?",
        "¿Eso es frecuente o raro?",
        "¿Te sucede seguido?",
        "¿Es algo que ocurre cada semana?",
        "¿Te pasa una vez al mes o más?",
        "¿Te ha pasado más de una vez esta semana?",
        "¿Es algo que aparece varias veces al día?",
        "¿Con qué regularidad tienes estos síntomas?",
        "¿Cada cuánto te viene ese dolor?",
        "¿Esto te pasa todo el tiempo?",
        "¿Desde hace cuánto ocurre con esa frecuencia?",
        "¿Lo notas más en algún momento del día?",
        "¿Te sucede por temporadas?",
        "¿Pasa a diario o solo a veces?",
        "¿Ese dolor viene y va seguido?",
        "¿Se presenta más de una vez al día?",
        "¿Esto aparece con frecuencia?",
        "¿Es algo constante o intermitente?",
        "¿Desde cuándo es tan seguido?",
        "¿Esto ocurre ocasionalmente o seguido?",
        "¿Sucede por las noches o durante el día?",
        "¿Lo notas más en las mañanas?",
        "¿Te ocurre mientras haces algo en particular?",
        "¿Se repite ese síntoma durante el día?"
    ],
    "intensidad": [
        "¿Qué tan fuerte es el dolor que siente?",
        "¿Puede calificar el dolor del 1 al 10?",
        "¿Diría que el dolor es leve, moderado o fuerte?",
        "¿Es un dolor soportable o insoportable?",
        "¿Qué nivel de intensidad tiene el dolor?",
        "¿El dolor es agudo o más bien leve?",
        "¿Se siente una presión intensa o ligera?",
        "¿El malestar es intenso o tolerable?",
        "¿Es un dolor constante y fuerte?",
        "¿Cómo describiría la severidad del dolor?",
        "¿El dolor le impide hacer sus actividades?",
        "¿El nivel del dolor cambia o se mantiene fuerte?",
        "¿Qué grado de intensidad siente cuando duele?",
        "¿El dolor es lo suficientemente fuerte como para detenerse?",
        "¿Es una molestia apenas perceptible o muy clara?",
        "¿Podría comparar el dolor con algo conocido en intensidad?",
        "¿Es un dolor incapacitante?",
        "¿Cuánto le duele exactamente?",
        "¿El dolor lo obliga a acostarse o detenerse?",
        "¿Es un malestar leve que puede ignorar?",
        "¿Le hace llorar o le quita el aliento?",
        "¿Es un dolor punzante que no lo deja en paz?",
        "¿Se siente presionado por el dolor?",
        "¿Es tan fuerte que no puede concentrarse?",
        "¿Lo despierta el dolor durante la noche?",
        "¿Podría seguir con su día normal con este nivel de dolor?",
        "¿Necesita medicación para calmar el dolor?",
        "¿El dolor lo deja sin energía o fuerzas?",
        "¿Siente que el dolor empeora a lo largo del día?",
        "¿Es un dolor intermitente o siempre intenso?",
        "¿El dolor aparece con una intensidad inesperada?",
        "¿Se siente desbordado por la intensidad del dolor?",
        "¿Es un dolor que se extiende con fuerza?",
        "¿Lo obliga a detener cualquier tarea que realice?",
        "¿El malestar es tan fuerte que no puede hablar bien?",
        "¿Le genera náuseas por la intensidad?",
        "¿Ha sentido antes un dolor tan intenso?",
        "¿Le genera angustia el nivel del dolor?",
        "¿El dolor lo hace sudar o temblar?",
        "¿Se siente al borde del colapso por el dolor?",
        "¿Puede caminar o moverse con ese dolor?",
        "¿El dolor lo hace llorar o gritar?",
        "¿Es similar a una crisis dolorosa?",
        "¿Podría soportar este dolor por mucho tiempo?",
        "¿Necesita sentarse o recostarse por el dolor?",
        "¿El dolor le nubla la vista por la intensidad?",
        "¿Siente que el dolor domina todo su cuerpo?",
        "¿Es tan intenso que necesita ayuda inmediata?",
        "¿Es el dolor lo peor que ha sentido?",
        "¿El nivel de dolor es similar al de una cirugía?",
        "¿Qué tan fuerte dirías que es el dolor?",
        "Si tuvieras que ponerle un número del 1 al 10, ¿cuánto sería?",
        "¿Es un dolor leve o te llega a tumbar?",
        "¿Puedes seguir con tus actividades cuando te pasa?",
        "¿Te deja descansar o no puedes ni dormir?",
        "¿Lo soportas bien o es muy molesto?",
        "¿Te impide hacer tus cosas?",
        "¿Es un dolor que se siente fuerte desde el inicio o va subiendo?",
        "¿Te ha dolido más que otras veces?",
        "¿Es peor que otras veces o más suave?",
        "¿Ha cambiado la intensidad con el tiempo?",
        "¿Hay momentos en que se siente más fuerte?",
        "¿A qué hora del día te duele más?",
        "¿Sientes que es un dolor que podrías ignorar o no se puede?",
        "¿Te ha llegado a hacer llorar o a gritar del dolor?",
        "¿Es un dolor muy fuerte?",
        "¿Te duele mucho o poquito?",
        "¿Lo puedes soportar o es muy intenso?",
        "¿Ese dolor te impide hacer cosas?",
        "¿Qué tan feo se siente el dolor?",
        "¿Te desespera el dolor?",
        "¿Ese dolor te hace llorar?",
        "¿Es un dolor que no puedes ignorar?",
        "¿Te cuesta dormir por el dolor?",
        "¿Es una molestia leve o intensa?",
        "¿Se siente más como una incomodidad o como algo fuerte?",
        "¿El dolor es insoportable?",
        "¿Ese dolor te paraliza?",
        "¿Te deja hacer tus actividades normales?",
        "¿Cuánto te molesta en el día a día?",
        "¿Lo calificarías como un dolor leve?",
        "¿Dirías que es algo molesto o doloroso?",
        "¿En qué nivel está del 1 al 10?",
        "¿Sientes que aumenta con el paso del día?",
        "¿Es un dolor punzante o solo molesto?",
        "¿Te interfiere con tu rutina?",
        "¿Te obliga a detenerte cuando aparece?",
        "¿Te duele solo un poco o mucho?",
        "¿Ese dolor te hace sentarte o acostarte?",
        "¿Te ha dejado sin poder moverte?"
    ],
    "localizacion": [
        "¿Dónde siente exactamente el dolor?",
        "¿En qué parte del cuerpo se localiza el malestar?",
        "¿Podría señalar dónde le duele?",
        "¿El dolor está ubicado en un solo lugar?",
        "¿Se presenta en el lado derecho o izquierdo?",
        "¿Siente el dolor en la cabeza, abdomen o espalda?",
        "¿Dónde comienza el dolor?",
        "¿El malestar está en las extremidades?",
        "¿Le duele el pecho o el estómago?",
        "¿Siente dolor en los músculos o las articulaciones?",
        "¿Dónde nota el punto más intenso del dolor?",
        "¿Está focalizado en una zona específica?",
        "¿El dolor aparece en más de una región?",
        "¿Tiene dolor en la parte superior del cuerpo?",
        "¿Está en la pierna, brazo, cuello u otra zona?",
        "¿Siente una presión localizada?",
        "¿Puede identificar la zona exacta del dolor?",
        "¿Es un dolor abdominal, torácico o cefálico?",
        "¿Lo siente en la parte trasera o delantera del cuerpo?",
        "¿Se presenta más en la parte interna o externa?",
        "¿Afecta una sola parte del cuerpo o varias?",
        "¿Siente el dolor cerca de los órganos internos?",
        "¿El dolor se siente superficial o profundo?",
        "¿Está presente en la parte baja de la espalda?",
        "¿Es un dolor central o lateralizado?",
        "¿Tiene molestias en la nuca o las sienes?",
        "¿Se sitúa en los costados o el centro del abdomen?",
        "¿El malestar se presenta en la pelvis?",
        "¿Está localizado en la región lumbar?",
        "¿Siente dolor en las manos o en los pies?",
        "¿Está en la zona ocular, nasal o auditiva?",
        "¿Le duele una articulación específica?",
        "¿El dolor está en el área torácica?",
        "¿Es un dolor que se localiza en el rostro?",
        "¿Le duele el cuero cabelludo?",
        "¿Siente el dolor en la columna vertebral?",
        "¿En qué área corporal comenzó el síntoma?",
        "¿Dónde se manifiesta más el malestar?",
        "¿Le molesta una zona concreta?",
        "¿Siente la molestia en la parte interna del muslo?",
        "¿La molestia se concentra en un solo punto?",
        "¿El dolor está confinado a una zona pequeña?",
        "¿En qué zona corporal nota el dolor con más fuerza?",
        "¿Se ubica el dolor en los glúteos?",
        "¿El malestar se extiende desde un punto específico?",
        "¿La zona del dolor cambia o es fija?",
        "¿Siente que una zona está más afectada que otras?",
        "¿Hay un lugar que le duela al presionarlo?",
        "¿El dolor se limita a una parte específica del cuerpo?",
        "¿Se encuentra el dolor cerca de la piel o más profundo?",
        "¿Dónde te duele exactamente?",
        "¿En qué parte del cuerpo sientes el dolor?",
        "¿Puedes señalar con el dedo dónde sientes la molestia?",
        "¿Está en un solo lugar o se mueve?",
        "¿El dolor se concentra en un punto o es más general?",
        "¿Te molesta más de un lado del cuerpo?",
        "¿Lo sientes más en la cabeza, el cuello o en otra zona?",
        "¿Hay una parte que te duela más que otra?",
        "¿Te molesta más al tocar cierta zona?",
        "¿En qué zona empezó el dolor?",
        "¿Está más hacia el lado izquierdo o el derecho?",
        "¿Sientes la molestia más por dentro o por fuera?",
        "¿Lo notas más cerca de la piel o más profundo?",
        "¿Te duele en una zona específica o en varias?",
        "¿Se concentra en la nuca, frente, sien o en todo el cráneo?",
        "¿Dónde exactamente te duele?",
        "¿En qué parte del cuerpo lo sientes?",
        "¿El dolor está más arriba o más abajo?",
        "¿Es en un solo lado o en ambos?",
        "¿Te molesta en el pecho o en el estómago?",
        "¿Está localizado o es general?",
        "¿Puedes tocar el lugar que duele?",
        "¿Te molesta más en la espalda o al frente?",
        "¿Es más en la cabeza o en el cuello?",
        "¿En qué zona notas la molestia?",
        "¿Te duele el abdomen o más bien el costado?",
        "¿Sientes dolor en los músculos o en las articulaciones?",
        "¿Te molesta en la pierna o en el brazo?",
        "¿Te duele por dentro o por fuera?",
        "¿Es en la piel o más profundo?",
        "¿La molestia está en una zona específica?",
        "¿En qué parte del cuerpo lo notas primero?",
        "¿Es más bien interno o superficial?",
        "¿Dónde empieza el dolor?",
        "¿Lo notas más de un lado que del otro?",
        "¿Te duele el lado izquierdo?",
        "¿Está en la parte baja de la espalda?",
        "¿Lo sientes en el pecho o el corazón?",
        "¿Molesta más al tocarlo?",
        "¿Puedes mostrarme con el dedo dónde duele?"
    ],
    "agravamiento": [
        "¿Hay algo que empeore el dolor?",
        "¿El dolor se agrava con el movimiento?",
        "¿Notas si algo lo intensifica?",
        "¿Empeora cuando haces ejercicio?",
        "¿Se vuelve más fuerte al caminar?",
        "¿La luz brillante lo agrava?",
        "¿El ruido fuerte hace que aumente?",
        "¿El estrés hace que se intensifique?",
        "¿Sientes que la comida lo empeora?",
        "¿Los cambios de clima afectan el dolor?",
        "¿Aumenta cuando no duerme bien?",
        "¿Se agrava con ciertos olores?",
        "¿Alguna actividad lo vuelve más severo?",
        "¿Notas que el dolor crece al agacharte?",
        "¿Sentarse lo hace peor?",
        "¿Al estar de pie por mucho tiempo se agrava?",
        "¿El dolor se intensifica al cargar peso?",
        "¿Las emociones fuertes aumentan el dolor?",
        "¿Cuando está en tensión el dolor crece?",
        "¿El dolor empeora si no toma medicamentos?",
        "¿Comer ciertos alimentos lo hace más fuerte?",
        "¿El café o el alcohol afectan el malestar?",
        "¿El dolor crece con el esfuerzo físico?",
        "¿Le afecta más en lugares con ruido?",
        "¿El calor o el frío intensifican el dolor?",
        "¿Cambiar de postura lo empeora?",
        "¿Los movimientos bruscos aumentan el dolor?",
        "¿Toser o estornudar agravan el malestar?",
        "¿El dolor empeora si se mueve rápido?",
        "¿Al subir escaleras lo siente más fuerte?",
        "¿Después de comer lo siente más?",
        "¿El dolor aparece tras realizar alguna tarea?",
        "¿Con ciertos movimientos siente más dolor?",
        "¿La ansiedad o preocupación lo agravan?",
        "¿Estar en lugares cerrados afecta el dolor?",
        "¿Con el paso de las horas aumenta el dolor?",
        "¿El dolor se hace peor por la tarde o noche?",
        "¿Cuando se levanta rápido duele más?",
        "¿Al girar el cuerpo el dolor aumenta?",
        "¿La menstruación influye en el dolor?",
        "¿Hay posturas que empeoran el síntoma?",
        "¿Lo siente más cuando está bajo presión?",
        "¿La falta de descanso lo hace más agudo?",
        "¿Los esfuerzos repetitivos lo intensifican?",
        "¿Hay sonidos que provocan más dolor?",
        "¿Movimientos repetidos agravan la molestia?",
        "¿Se intensifica si no descansa bien?",
        "¿Hay situaciones que agravan el malestar?",
        "¿Al estar en lugares calurosos lo nota más?",
        "¿Qué cosas sabe que empeoran el dolor?",
        "¿Hay algo que haga que el dolor empeore?",
        "¿Notas si al moverte te duele más?",
        "¿Te molesta más cuando te agachas o giras la cabeza?",
        "¿Ciertas luces, ruidos o movimientos lo empeoran?",
        "¿Empeora cuando haces ejercicio o algún esfuerzo?",
        "¿Notas que empeora cuando no duermes bien?",
        "¿Cambia con el estrés o emociones fuertes?",
        "¿Con el calor o el frío lo sientes más fuerte?",
        "¿Comer ciertos alimentos lo empeora?",
        "¿Te ha pasado que te duele más después de usar el celular o la computadora?",
        "¿Sientes que la luz o el sonido aumentan el malestar?",
        "¿Te molesta más si te acuestas o si te levantas rápido?",
        "¿Te duele más al tocar esa zona?",
        "¿Ciertas posturas agravan el dolor?",
        "¿Alguna actividad del día a día hace que el dolor aumente?",
        "¿Hay algo que lo empeore?",
        "¿Te duele más cuando te mueves?",
        "¿Empeora al comer algo?",
        "¿Lo sientes más cuando estás acostado?",
        "¿El dolor aumenta con el esfuerzo?",
        "¿Te duele más después de caminar?",
        "¿Notas si con el frío empeora?",
        "¿El dolor se pone peor cuando respiras profundo?",
        "¿Al hacer ejercicio empeora?",
        "¿Sientes que con ciertas posturas se agrava?",
        "¿Te afecta más si estás estresado?",
        "¿Empeora al agacharte?",
        "¿Te duele más por las noches?",
        "¿Con qué actividad empeora?",
        "¿Al subir escaleras se pone peor?",
        "¿Hay algo que claramente lo dispare?",
        "¿Notas si se agrava con ciertos alimentos?",
        "¿Se intensifica si estás mucho tiempo sentado?",
        "¿Empeora cuando estás de pie mucho tiempo?",
        "¿Te afecta más si comes pesado?",
        "¿La molestia aumenta al toser?",
        "¿Te sientes peor si duermes poco?",
        "¿Con el calor se intensifica?",
        "¿Empeora cuando estás nervioso?",
        "¿Hay algo que definitivamente lo haga más fuerte?"
    ],
    "inicio": [
        "¿Desde cuándo comenzó el dolor?",
        "¿Cuándo notó por primera vez los síntomas?",
        "¿Recuerda el momento en que empezó el malestar?",
        "¿El dolor inició hace mucho o poco tiempo?",
        "¿Cuánto tiempo ha pasado desde que empezó?",
        "¿Desde qué día tiene esta molestia?",
        "¿Cuándo aparecieron los síntomas por primera vez?",
        "¿Hace cuánto que tiene este problema?",
        "¿Puede decirme cuándo comenzó exactamente?",
        "¿Fue repentino o progresivo el inicio del dolor?",
        "¿El malestar apareció hace unos días o semanas?",
        "¿Esto empezó recientemente?",
        "¿Desde hace cuánto nota los síntomas?",
        "¿Desde hace cuántas horas lo siente?",
        "¿El dolor empezó esta semana?",
        "¿Fue un inicio súbito o gradual?",
        "¿Cuándo comenzó este episodio?",
        "¿Este dolor lo tiene desde ayer o antes?",
        "¿Cuánto tiempo lleva con esta dolencia?",
        "¿Esto inició hace más de una semana?",
        "¿Puede identificar cuándo fue el inicio exacto?",
        "¿Sabe si empezó tras algún evento?",
        "¿Se presentó de forma inesperada?",
        "¿Cuándo notó que algo andaba mal?",
        "¿Sabe qué día comenzaron los síntomas?",
        "¿Hace cuánto se siente así?",
        "¿Puede estimar desde cuándo tiene este malestar?",
        "¿Recuerda si fue reciente o de hace meses?",
        "¿Hace días que lo padece?",
        "¿Desde cuándo tiene molestias similares?",
        "¿Esto comenzó de forma lenta o abrupta?",
        "¿El primer síntoma fue hace cuánto?",
        "¿Empezó hace unas horas o días?",
        "¿Este dolor lo acompaña desde cuándo?",
        "¿Notó los síntomas desde hace tiempo?",
        "¿Hace cuánto ocurrió el primer episodio?",
        "¿Desde qué fecha tiene el problema?",
        "¿Puede señalar el día del inicio?",
        "¿El inicio fue repentino o paulatino?",
        "¿Cuándo fue la primera vez que lo notó?",
        "¿Desde hace cuánto lo experimenta?",
        "¿Lo sufre desde algún momento específico?",
        "¿Desde qué evento cree que comenzó?",
        "¿Desde cuándo siente que algo no está bien?",
        "¿Hace cuánto empezó a sentir molestias?",
        "¿Este malestar comenzó esta semana?",
        "¿El dolor surgió de la nada o fue aumentando?",
        "¿Esto viene ocurriendo desde hace cuánto?",
        "¿Tiene una idea del momento en que comenzó?",
        "¿Desde qué día exacto tiene el síntoma?",
        "¿Desde cuándo empezaste con estos síntomas?",
        "¿Recuerdas cuándo fue la primera vez que sentiste este dolor?",
        "¿Esto empezó de repente o fue poco a poco?",
        "¿Hace cuánto te empezó a doler?",
        "¿Hubo algo que creas que lo detonó?",
        "¿Fue después de algún esfuerzo, caída o golpe?",
        "¿Esto comenzó hace días, semanas o más tiempo?",
        "¿Te despertaste con el dolor o apareció durante el día?",
        "¿Fue después de una situación de estrés o tensión?",
        "¿Se presentó por primera vez en la mañana, tarde o noche?",
        "¿Esto es reciente o ya lo habías sentido antes?",
        "¿Cuánto tiempo ha pasado desde la primera molestia?",
        "¿Es algo que apareció por primera vez hoy?",
        "¿Fue gradual o repentino el inicio del dolor?",
        "¿Comenzó leve y fue aumentando o ya empezó fuerte?",
        "¿Cuándo comenzó esto?",
        "¿Desde hace cuánto tiempo tienes ese dolor?",
        "¿Hace cuánto empezó la molestia?",
        "¿Cuándo notaste por primera vez el síntoma?",
        "¿Desde qué día te duele?",
        "¿Recuerdas cuándo comenzó?",
        "¿Esto empezó de repente o poco a poco?",
        "¿Hace días, semanas o meses que te pasa?",
        "¿Hace cuánto empezó a sentirse mal?",
        "¿Cuándo fue la primera vez que te dolió?",
        "¿Hace cuánto que te sientes así?",
        "¿El dolor inició hace poco o hace rato?",
        "¿Cuándo notaste el cambio?",
        "¿Desde cuándo tienes esa sensación?",
        "¿Esto empezó hoy o hace tiempo?",
        "¿Cuánto tiempo llevas con esto?",
        "¿Cuándo empezó a empeorar?",
        "¿Recuerdas el momento exacto?",
        "¿Cuándo fue el primer síntoma?",
        "¿Cuánto hace que te duele eso?",
        "¿Cuándo apareció por primera vez?",
        "¿Hace cuánto comenzó la molestia?",
        "¿Desde cuándo sientes eso?",
        "¿Cuándo notaste que empezó a doler?",
        "¿Esto inició hace poco o ya es viejo?"
    ],
    "irradiacion": [
        "¿El dolor se expande hacia otras zonas del cuerpo?",
        "¿Siente que el dolor se irradia?",
        "¿El dolor se mueve o permanece en un solo lugar?",
        "¿Se extiende el dolor a otras partes?",
        "¿El malestar recorre otras regiones de su cuerpo?",
        "¿El dolor se propaga desde donde empezó?",
        "¿Lo siente en una zona y luego en otra?",
        "¿Siente que el dolor viaja por el cuerpo?",
        "¿La molestia aparece también en otras áreas?",
        "¿El dolor afecta también a los brazos o piernas?",
        "¿El dolor se traslada a otras partes del cuerpo?",
        "¿Empieza en un lugar y se expande?",
        "¿La sensación de dolor cambia de ubicación?",
        "¿El malestar se irradia a otras áreas?",
        "¿Siente el dolor en varias partes a la vez?",
        "¿El dolor se manifiesta en otra zona también?",
        "¿Nota que se irradia hacia el cuello o espalda?",
        "¿El dolor sube o baja a lo largo del cuerpo?",
        "¿El dolor se refleja en otras áreas?",
        "¿Se presenta en un sitio y luego en otro?",
        "¿Hay una zona donde comienza y otra donde termina?",
        "¿El dolor sigue un trayecto corporal?",
        "¿Se irradia hacia alguna extremidad?",
        "¿Siente que el dolor corre por el cuerpo?",
        "¿Se desplaza la molestia con el tiempo?",
        "¿Se expande desde el centro hacia afuera?",
        "¿A veces cambia de zona?",
        "¿El dolor afecta también otras áreas contiguas?",
        "¿Siente que se mueve a lo largo del día?",
        "¿Afecta también zonas alejadas del punto inicial?",
        "¿Se presenta en un lado y luego en otro?",
        "¿Lo siente en diferentes niveles del cuerpo?",
        "¿El dolor sube desde el abdomen al pecho?",
        "¿Se propaga por la espalda?",
        "¿Irradia hacia la mandíbula u oído?",
        "¿La molestia va desde un punto a varios más?",
        "¿Se nota el dolor en otras regiones también?",
        "¿Se ramifica la sensación del dolor?",
        "¿Abarca más que un solo sitio?",
        "¿Siente que corre hacia el brazo o pierna?",
        "¿Se expande por el torso?",
        "¿Siente dolor reflejado en otra parte?",
        "¿Irradia a zonas alejadas del lugar de inicio?",
        "¿Siente el mismo dolor en zonas simétricas?",
        "¿Se repite el malestar en áreas distintas?",
        "¿Es un dolor que se distribuye por el cuerpo?",
        "¿Aparece en varios puntos relacionados?",
        "¿Siente que el dolor fluye o se dispersa?",
        "¿El dolor toma un camino por el cuerpo?",
        "¿Irradia hacia la espalda baja o los hombros?",
        "¿Sientes que el dolor se corre hacia otra parte?",
        "¿El dolor se mueve a otras zonas del cuerpo?",
        "¿Empieza en un lugar y luego se extiende?",
        "¿Sientes que el dolor viaja por el cuello o la espalda?",
        "¿Va desde la cabeza hacia los ojos o la mandíbula?",
        "¿Te baja hacia los hombros o brazos?",
        "¿El dolor cambia de lugar o siempre es el mismo?",
        "¿Lo sientes solo en un punto o en varios?",
        "¿Sientes que se va expandiendo con el tiempo?",
        "¿Irradia hacia un lado más que al otro?",
        "¿El malestar se extiende hacia la nuca o la espalda?",
        "¿Llega a sentirse en la cara o en el cuello?",
        "¿Se va moviendo conforme pasan las horas?",
        "¿Hay zonas a las que se ha ido corriendo el dolor?",
        "¿Sientes como si el dolor caminara por la cabeza?",
        "¿El dolor se mueve a otro lado?",
        "¿Sientes que el dolor se extiende?",
        "¿Se te irradia el dolor hacia el brazo o la pierna?",
        "¿El dolor se expande a otras zonas?",
        "¿Se siente en un solo lugar o se va a otro sitio?",
        "¿Se mueve el dolor o se queda fijo?",
        "¿El dolor viaja hacia la espalda o el pecho?",
        "¿Sientes que el dolor baja por la pierna?",
        "¿Se irradia hacia el cuello o los hombros?",
        "¿El dolor se va hacia el lado izquierdo o derecho?",
        "¿Sientes que el dolor pasa a otra parte?",
        "¿El dolor cambia de lugar con el tiempo?",
        "¿Se extiende o permanece en un punto?",
        "¿El dolor se propaga a otras áreas?",
        "¿Sientes que se mueve o que es local?",
        "¿El dolor irradia hacia otras partes del cuerpo?",
        "¿Se siente que el dolor corre por el brazo?",
        "¿El dolor baja o sube de lugar?",
        "¿Sientes que se esparce o que es puntual?",
        "¿Se irradia hacia la cabeza o la mandíbula?",
        "¿El dolor se expande al moverte?",
        "¿Sientes que se propaga hacia la espalda?",
        "¿El dolor va hacia el abdomen o la pelvis?",
        "¿Se mueve con el tiempo o es fijo?",
        "¿Sientes que se distribuye en otra zona?"
    ],
    "descripcion_dolor": [
        "¿Cómo describiría el tipo de dolor que siente?",
        "¿El dolor es punzante, ardoroso o sordo?",
        "¿Es una presión, un pinchazo o una quemazón?",
        "¿Siente que le pulsa o le aprieta?",
        "¿El dolor es constante o intermitente?",
        "¿Tiene forma de latido o es más bien una presión?",
        "¿Es un dolor agudo o más bien suave?",
        "¿La molestia es como un choque eléctrico?",
        "¿Le arde o quema la zona afectada?",
        "¿Lo siente como una punzada o como tensión?",
        "¿Es una sensación que va y viene?",
        "¿El dolor es como un calambre?",
        "¿Se siente como si lo apretaran fuerte?",
        "¿Es más bien un dolor sordo o vibrante?",
        "¿Siente un golpe interno o una presión localizada?",
        "¿El dolor se parece a un tirón muscular?",
        "¿Es como si algo lo quemara por dentro?",
        "¿Siente presión, hormigueo o dolor punzante?",
        "¿Lo siente como si algo le estallara dentro?",
        "¿La molestia es fuerte como un martilleo?",
        "¿Podría compararlo con un pinchazo de aguja?",
        "¿Es como si lo estuvieran apretando con fuerza?",
        "¿Tiene una sensación opresiva o expansiva?",
        "¿Es un dolor que pica, arde o quema?",
        "¿Le duele como si se estirara algo por dentro?",
        "¿Es un dolor seco o húmedo, profundo o superficial?",
        "¿Lo siente como una corriente eléctrica?",
        "¿Es un dolor que da puntadas o como cuchilladas?",
        "¿La sensación es más como presión o como ardor?",
        "¿Es como si le clavaran algo?",
        "¿Es constante o aparece por momentos?",
        "¿Siente espasmos dolorosos?",
        "¿Es como si se inflamaran los tejidos?",
        "¿Siente rigidez junto con dolor?",
        "¿El dolor se intensifica con el movimiento o al respirar?",
        "¿Es una molestia que impide pensar claramente?",
        "¿Es como una presión desde adentro hacia afuera?",
        "¿Siente como si se expandiera en oleadas?",
        "¿El dolor tiene forma de palpitación?",
        "¿Lo compararía con una presión creciente?",
        "¿Siente que el dolor gira o vibra?",
        "¿Es una molestia parecida a un ardor solar?",
        "¿Tiene una sensación de opresión en la zona?",
        "¿Es un dolor parecido al de una migraña fuerte?",
        "¿La molestia es sutil o bien definida?",
        "¿Siente que lo comprimen o le halan algo dentro?",
        "¿Lo describiría como una corriente pulsante?",
        "¿El dolor lo siente como algo expansivo?",
        "¿Es como si le punzaran en intervalos?",
        "¿Tiene forma de espasmo o descarga?",
        "¿Cómo describirías ese dolor que tienes?",
        "¿Es más como un pinchazo, una presión o una punzada?",
        "¿Sientes ardor, latido, presión o algo más?",
        "¿Parece que pulsa, arde o quema?",
        "¿Es constante o intermitente?",
        "¿Lo sientes como si te apretaran la cabeza?",
        "¿Es una molestia leve o se siente punzante?",
        "¿Te duele como si algo latiera en tu cabeza?",
        "¿Dirías que es una presión o un ardor?",
        "¿Es un dolor seco o más bien como quemante?",
        "¿Te da la sensación de tener algo pesado encima?",
        "¿Es un dolor que va y viene o se queda fijo?",
        "¿Parece que te taladraran o más bien que te aprietan?",
        "¿Se siente como calor o como golpes internos?",
        "¿El dolor se siente agudo o como una molestia difusa?",
        "¿El dolor es punzante o más bien sordo?",
        "¿Se siente como una quemazón o ardor?",
        "¿Es un dolor constante o que va y viene?",
        "¿El dolor es como un pinchazo?",
        "¿Sientes una presión en esa zona?",
        "¿Es un dolor agudo o más bien leve?",
        "¿Se siente como un calambre?",
        "¿El dolor es profundo o superficial?",
        "¿Es un dolor que molesta o que incapacita?",
        "¿Sientes que el dolor es eléctrico?",
        "¿Es un dolor que se siente caliente o frío?",
        "¿Es más bien un dolor sordo y molesto?",
        "¿El dolor es cortante o rasposo?",
        "¿Sientes que te quema o te oprime?",
        "¿Es un dolor que pica o arde?",
        "¿Se siente como un latido fuerte?",
        "¿Es un dolor suave o intenso?",
        "¿Se siente como si algo se presionara?",
        "¿Es un dolor que se siente en la piel o dentro?",
        "¿Sientes que es un dolor profundo y constante?",
        "¿Es un dolor que se va y vuelve?",
        "¿Se siente como un choque eléctrico?",
        "¿Es un dolor que te despierta por la noche?",
        "¿Se siente como una molestia punzante?",
        "¿Es un dolor que se extiende o es puntual?"
    ],
    "sintomas": [
        "¿Tiene algún otro síntoma además del dolor?",
        "¿Presenta fiebre, náuseas u otra molestia?",
        "¿Experimenta escalofríos o sudoración?",
        "¿Ha notado mareos o vómito?",
        "¿Acompaña al dolor algún otro malestar?",
        "¿Siente debilidad o fatiga?",
        "¿Tiene visión borrosa o dificultad para concentrarse?",
        "¿Ha perdido el apetito últimamente?",
        "¿Siente molestias estomacales además del dolor?",
        "¿Tiene algún síntoma adicional?",
        "¿Se le dificulta respirar?",
        "¿Presenta zumbidos en los oídos?",
        "¿Siente hormigueo o adormecimiento?",
        "¿Ha tenido desmayos o episodios de confusión?",
        "¿Ha notado palpitaciones o taquicardias?",
        "¿Siente rigidez o tensión muscular?",
        "¿Tiene temblores o movimientos involuntarios?",
        "¿Sufre cambios de temperatura corporal?",
        "¿Siente presión en el pecho?",
        "¿Ha notado sudoraciones nocturnas?",
        "¿Tiene sensibilidad a la luz o al sonido?",
        "¿Ha tenido dificultad para dormir?",
        "¿Ha perdido peso sin razón aparente?",
        "¿Siente náuseas constantes?",
        "¿Tiene sensación de malestar general?",
        "¿Ha tenido alteraciones en el ritmo cardíaco?",
        "¿Nota entumecimiento en alguna parte del cuerpo?",
        "¿Siente inflamación o hinchazón?",
        "¿Tiene dificultad para hablar o moverse?",
        "¿Siente que pierde el equilibrio?",
        "¿Ha notado cambios en la presión arterial?",
        "¿Ha tenido fiebre en los últimos días?",
        "¿Siente que le falta energía?",
        "¿Tiene molestias al orinar?",
        "¿Experimenta dolor en más de una parte del cuerpo?",
        "¿Se le dificulta comer o tragar?",
        "¿Tiene visión doble o borrosa?",
        "¿Ha sentido sensación de desmayo?",
        "¿Siente frío constante sin causa evidente?",
        "¿Tiene tos persistente u otro síntoma respiratorio?",
        "¿Sufre de cambios de humor inusuales?",
        "¿Nota su pulso acelerado sin motivo?",
        "¿Siente presión en la cabeza?",
        "¿Tiene problemas para mantenerse en pie?",
        "¿Ha tenido cambios en su apetito?",
        "¿Siente que su cuerpo no responde como antes?",
        "¿Tiene dificultad para concentrarse?",
        "¿Siente tensión en el cuello o espalda?",
        "¿Percibe debilidad en alguna extremidad?",
        "¿Tiene sensación de ardor o picor sin lesión visible?",
        "¿Tienes algún otro síntoma además del dolor?",
        "¿Has sentido náuseas, mareos o vómitos?",
        "¿Te ha dado fiebre o escalofríos últimamente?",
        "¿Sientes visión borrosa o sensibilidad a la luz?",
        "¿Has notado zumbido en los oídos?",
        "¿Tienes debilidad o sensación de desmayo?",
        "¿Sientes cansancio extremo o fatiga?",
        "¿Has perdido el apetito o el sueño?",
        "¿Te sientes confundido o con dificultad para concentrarte?",
        "¿Te han dado sudores fríos o calor repentino?",
        "¿Hay sensación de presión en el pecho o dificultad para respirar?",
        "¿Sientes hormigueo en alguna parte del cuerpo?",
        "¿Tienes rigidez en el cuello o en otra parte?",
        "¿Has tenido cambios en el ritmo cardíaco?",
        "¿Hay algún otro síntoma que se presente junto con el dolor?",
        "¿Tienes fiebre o escalofríos?",
        "¿Has notado náuseas o vómitos?",
        "¿Presentas tos o dificultad para respirar?",
        "¿Sientes cansancio o debilidad?",
        "¿Tienes dolor de cabeza o mareos?",
        "¿Has tenido sudoración excesiva?",
        "¿Sientes hinchazón en alguna parte?",
        "¿Has notado pérdida de apetito?",
        "¿Tienes congestión o secreción nasal?",
        "¿Sientes picazón o ardor?",
        "¿Presentas dolor al orinar?",
        "¿Has tenido diarrea o estreñimiento?",
        "¿Tienes sensación de ardor en el pecho?",
        "¿Sientes zumbido en los oídos?",
        "¿Has notado cambios en la piel?",
        "¿Presentas dolor muscular o articular?",
        "¿Sientes dificultad para dormir?",
        "¿Has tenido pérdida de peso sin causa?",
        "¿Presentas temblores o espasmos?",
        "¿Tienes dificultad para tragar?",
        "¿Sientes dolor al moverte?",
        "¿Has notado cambios en la visión?",
        "¿Sientes debilidad en alguna parte del cuerpo?",
        "¿Has presentado moretones sin motivo?",
        "¿Tienes sensación de opresión en el pecho?"
    ],
    "medicamento": [
        "¿Ha tomado algún medicamento para aliviar el dolor?",
        "¿Qué pastillas ha usado recientemente?",
        "¿Está usando algún fármaco para tratar los síntomas?",
        "¿Se automedicó antes de venir a consulta?",
        "¿Está en algún tratamiento actualmente?",
        "¿Qué remedios ha probado hasta ahora?",
        "¿Tomó algo por su cuenta para el dolor?",
        "¿Qué tipo de analgésico ha ingerido?",
        "¿Ha usado paracetamol, ibuprofeno u otro medicamento?",
        "¿Le recetaron algo previamente?",
        "¿Sigue algún tratamiento médico por esta razón?",
        "¿Usó alguna medicina sin receta?",
        "¿Tomó algún antiinflamatorio últimamente?",
        "¿Inició algún tratamiento en casa?",
        "¿Ha ingerido algo para calmar los síntomas?",
        "¿Ha usado remedios naturales o caseros?",
        "¿Recibió medicamentos en una consulta previa?",
        "¿Está tomando algún medicamento ahora mismo?",
        "¿Recibió alguna indicación farmacológica reciente?",
        "¿Está tomando algo que le recomendaron familiares o amigos?",
        "¿Consiguió alguna medicina en la farmacia por su cuenta?",
        "¿Le recetaron algo en otra clínica?",
        "¿Está repitiendo alguna receta anterior?",
        "¿Tomó medicina de la última vez que sintió lo mismo?",
        "¿Pidió algo en la farmacia para esto?",
        "¿Ha tomado antibióticos por su cuenta?",
        "¿Tiene alguna receta que siga actualmente?",
        "¿Utilizó alguna pomada o parche?",
        "¿Usó gotas, jarabe u otra presentación?",
        "¿Aplicó algo en la zona afectada?",
        "¿Usa pastillas para el dolor frecuentemente?",
        "¿Tomó algo esta mañana o ayer?",
        "¿Se le indicó algún tratamiento y lo está siguiendo?",
        "¿Inició por su cuenta algún plan de medicación?",
        "¿Lleva más de un día tomando medicina?",
        "¿Usó medicamentos viejos que tenía en casa?",
        "¿Probó tratamientos alternativos o homeopatía?",
        "¿Está bajo supervisión médica con medicamentos?",
        "¿Usó medicamentos de otro padecimiento para esto?",
        "¿Tomó medicina que tenía guardada?",
        "¿Sigue usando el medicamento anterior?",
        "¿Probó algún calmante natural?",
        "¿Sigue tomando algo aunque ya se sienta mejor?",
        "¿Ha tomado analgésicos sin supervisión médica?",
        "¿Sabe el nombre del medicamento que usó?",
        "¿Ha tenido efectos con algún medicamento reciente?",
        "¿Le hizo efecto la medicina que tomó?",
        "¿Tomó más de una dosis?",
        "¿Tomó algo y no le funcionó?",
        "¿Empeoró después de usar alguna medicina?",
        "¿Has tomado algo para aliviar este dolor?",
        "¿Qué medicamento usaste por última vez?",
        "¿Te tomaste alguna pastilla antes de venir?",
        "¿Te automedicaste o alguien te recetó algo?",
        "¿Has usado algún analgésico o antiinflamatorio?",
        "¿Te ayudó algo de lo que tomaste?",
        "¿El medicamento te calmó el dolor o no hizo efecto?",
        "¿Hace cuánto tomaste la última dosis?",
        "¿Usaste algo natural o solo medicina convencional?",
        "¿Has probado con algún remedio casero?",
        "¿Has notado si alguna medicina te empeora los síntomas?",
        "¿Estás tomando otros medicamentos además de ese?",
        "¿Tomas algo regularmente que pueda influir en este dolor?",
        "¿Tuviste alguna reacción al medicamento?",
        "¿Has notado si algo te alivia más que otra cosa?",
        "¿Has tomado algún medicamento para esto?",
        "¿Qué pastillas has usado últimamente?",
        "¿Estás usando algún remedio casero o medicina?",
        "¿Has tomado algo para aliviar el dolor?",
        "¿Has usado algún antibiótico?",
        "¿Estás tomando algún medicamento recetado?",
        "¿Has probado algún analgésico?",
        "¿Estás tomando algo para la fiebre?",
        "¿Has usado cremas o ungüentos?",
        "¿Tomas algún medicamento para el asma?",
        "¿Estás usando inhaladores o aerosoles?",
        "¿Has tomado vitaminas o suplementos?",
        "¿Has usado algún descongestionante?",
        "¿Estás bajo tratamiento con algún fármaco?",
        "¿Has usado pastillas para la tos?",
        "¿Tomas algún medicamento para la presión?",
        "¿Has utilizado algún antiinflamatorio?",
        "¿Has tomado medicinas sin receta?",
        "¿Estás siguiendo algún tratamiento?",
        "¿Has usado algún jarabe para la tos?",
        "¿Tomas algo para controlar la ansiedad?",
        "¿Has tomado algún medicamento para el estómago?",
        "¿Estás tomando algo para el dolor de cabeza?",
        "¿Has usado algún producto para aliviar los síntomas?",
        "¿Has tomado algo para bajar la inflamación?"
    ],
    "diagnostico": [
        "El diagnóstico más probable es migraña.",
        "Parece que está sufriendo de cefalea tensional.",
        "Todo indica que podría ser una neuralgia.",
        "Es posible que tenga una migraña con aura.",
        "Los síntomas son compatibles con cefalea crónica.",
        "Parece tratarse de una jaqueca.",
        "El cuadro clínico sugiere una cefalea mixta.",
        "Este caso apunta a una migraña episódica.",
        "Podría estar presentando dolor de cabeza tensional.",
        "Este patrón se asocia con cefalea por estrés.",
        "La enfermedad parece ser migraña sin aura.",
        "Se observa una presentación típica de jaqueca común.",
        "Se trata probablemente de una cefalea de tipo tensional.",
        "El perfil del dolor coincide con migraña menstrual.",
        "El dolor se asemeja al de una cefalea cervicogénica.",
        "Parece tratarse de una cefalea inducida por medicamentos.",
        "Es un caso característico de dolor tensional crónico.",
        "Se sospecha una neuralgia del trigémino.",
        "Los hallazgos clínicos sugieren cefalea en racimos.",
        "Esto podría ser un episodio de cefalea por resaca.",
        "El dolor cumple criterios de migraña leve a moderada.",
        "Todo parece indicar que es una migraña recurrente.",
        "Tiene signos clásicos de jaqueca con fotofobia.",
        "Se ajusta al diagnóstico de cefalea primaria.",
        "Lo que describe suena como una cefalea secundaria.",
        "Es muy probable que se trate de una cefalea tensional leve.",
        "Podría diagnosticarse como migraña sin complicaciones.",
        "Todo indica que sufre cefalea relacionada con el sueño.",
        "La evaluación clínica sugiere una jaqueca típica.",
        "Este dolor es compatible con cefalea relacionada al estrés.",
        "Podría tratarse de una cefalea por alteración hormonal.",
        "Presenta un cuadro clínico de migraña crónica.",
        "El patrón de dolor apunta a cefalea hipnica.",
        "Este tipo de molestia es típico de cefalea tensional aguda.",
        "Podríamos estar ante una neuralgia postherpética.",
        "Este caso es representativo de cefalea en racimo.",
        "Parece tener una cefalea por privación de cafeína.",
        "La descripción concuerda con migraña vestibular.",
        "Es probable que tenga una cefalea postraumática.",
        "Se trata de un tipo de cefalea episódica frecuente.",
        "Corresponde a una cefalea de origen vascular.",
        "El dolor es característico de cefalea frontal.",
        "La sintomatología se relaciona con migraña digestiva.",
        "El perfil clínico indica una cefalea aguda intermitente.",
        "Sufre de una cefalea con componente visual significativo.",
        "Los síntomas sugieren una cefalea climatérica.",
        "Todo apunta a una cefalea tensional multifactorial.",
        "Se identifica una migraña de tipo familiar.",
        "Su condición parece ser migraña inducida por alimentos.",
        "Podría estar padeciendo cefalea del esfuerzo.",
        "Yo diría que lo más probable es que sea una migraña.",
        "Esto suena bastante a un dolor de cabeza por tensión.",
        "Parece que lo que tienes es una migraña con aura.",
        "Podría ser solo una jaqueca fuerte, nada grave.",
        "Esto que me cuentas se parece mucho a una neuralgia.",
        "Todo apunta a que es una migraña común.",
        "Suena a que es estrés lo que te está causando esto.",
        "Me hace pensar en un dolor de cabeza por falta de sueño.",
        "Podría ser algo relacionado con los nervios, como una neuralgia.",
        "Tiene pinta de ser un dolor de cabeza tensional.",
        "Tal vez sea algo hormonal, a veces eso causa migrañas.",
        "Puede que sea solo cansancio acumulado.",
        "No parece nada serio, seguramente es solo una migraña.",
        "Lo más seguro es que sea por deshidratación o falta de descanso.",
        "Por lo que me cuentas, parece una migraña leve.",
        "Usted padece de asma.",
        "Creo que tiene gripa.",
        "Me parece que usted sufre de sinusitis.",
        "Los síntomas indican que puede ser gastritis.",
        "Todo da indicios de que es asma.",
        "Esto podría tratarse de una infección viral.",
        "Por lo que describe, parece una migraña.",
        "Podría estar sufriendo de una sinusitis leve.",
        "Lo más probable es que tenga gripe.",
        "Esto suena a una infección respiratoria.",
        "Me inclino a pensar que es una alergia.",
        "Tiene toda la pinta de una migraña.",
        "Podría ser una faringitis.",
        "Parece un cuadro de estrés acumulado.",
        "Creo que se trata de una cefalea tensional.",
        "Tiene síntomas muy claros de bronquitis.",
        "Lo que usted tiene podría ser colitis.",
        "Diría que es un caso de resfriado común.",
        "Me parece un problema gástrico, tal vez gastritis.",
        "Esto parece más bien una contractura muscular.",
        "Suena mucho a un problema de ansiedad.",
        "Lo más probable es que esté lidiando con rinitis.",
        "Podría ser algo relacionado con reflujo ácido.",
        "Yo diría que tiene una infección en vías respiratorias.",
        "Todo indica que es un cuadro viral leve."
    ]
}

# Preparar datos
frases = []
etiquetas = []
for categoria, ejemplos in frases_por_categoria.items():
    frases.extend([preprocesar_texto(f) for f in ejemplos])
    etiquetas.extend([categoria] * len(ejemplos))

# Dividir datos
X_train, X_test, y_train, y_test = train_test_split(frases, etiquetas, test_size=0.2, random_state=42)

# Entrenar modelo
modelo = make_pipeline(TfidfVectorizer(), LogisticRegression(max_iter=1000))
modelo.fit(X_train, y_train)

# Evaluar modelo
y_pred = modelo.predict(X_test)
print(classification_report(y_test, y_pred))

# Guardar modelo
joblib.dump(modelo, "modelo_entrenado.pkl")
print("Modelo entrenado y guardado con éxito.")
