from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import joblib

# Preprocesamiento básico
def preprocesar_texto(texto):
    return texto.lower().strip()

# Frases por categoría (diversas y balanceadas)
frases_por_categoria = {
    "consulta": [
        "¿Cuál es el motivo de su visita?",
        "¿En qué puedo asistirlo hoy?",
        "¿Qué desea consultar conmigo?",
        "¿Qué problema de salud lo aqueja hoy?",
        "¿Por qué ha venido hoy?",
        "¿En qué aspecto necesita ayuda médica?",
        "¿Cuál es su motivo de consulta?",
        "¿Qué desea revisar hoy conmigo?",
        "¿Qué lo trae a esta consulta?",
        "¿Qué situación médica le preocupa?",
        "¿Qué síntoma quiere comentar?",
        "¿Qué le gustaría abordar en esta cita?",
        "¿Por qué decidió consultar hoy?",
        "¿Tiene alguna molestia reciente?",
        "¿Con qué puedo ayudarle hoy?",
        "¿Qué síntomas está presentando?",
        "¿Qué tema médico desea tratar?",
        "¿Hay algo en particular que lo incomoda?",
        "¿Qué inquietud médica tiene?",
        "¿Qué desea tratar el día de hoy?",
        "¿Hay algo que lo motivó a venir?",
        "¿Qué condición le preocupa?",
        "¿Viene por alguna molestia reciente?",
        "¿Qué lo motivó a hacer esta consulta?",
        "¿Vino por chequeo o por malestar?",
        "¿Tiene alguna duda médica que quiera resolver?",
        "¿Siente alguna molestia que deba atenderse?",
        "¿Por qué solicitó esta cita médica?",
        "¿Qué desea revisar conmigo hoy?",
        "¿Quiere hablar de algún síntoma en especial?",
        "¿Hay algo que esté afectando su salud?",
        "¿Le preocupa alguna condición médica específica?",
        "¿Tiene alguna dolencia de la cual quiera hablar?",
        "¿Qué quiere comunicar sobre su salud?",
        "¿Desea atención por algo en particular?",
        "¿Qué es lo que más le molesta últimamente?",
        "¿Tiene algo que quiera comentar médicamente?",
        "¿Está experimentando síntomas nuevos?",
        "¿Quiere contarme qué siente últimamente?",
        "¿Viene a consulta por algún motivo específico?",
        "¿Podría explicarme qué lo trajo hoy aquí?",
        "¿Hay alguna urgencia médica?",
        "¿Busca orientación médica general?",
        "¿Tiene alguna patología conocida?",
        "¿Busca confirmar algún diagnóstico?",
        "¿Vino para hablar de un tratamiento?",
        "¿Qué le gustaría tratar en la consulta?",
        "¿Tiene dudas sobre su condición actual?",
        "¿Hay síntomas que se hayan agravado?",
        "¿Tiene algún seguimiento pendiente?",
        "¿Quiere descartar alguna enfermedad?"
    ],
    "frecuencia": [
        "¿Con qué frecuencia se presentan los síntomas?",
        "¿Cada cuánto tiempo ocurre el dolor?",
        "¿Esto sucede todos los días o solo a veces?",
        "¿Cuántas veces por semana siente molestias?",
        "¿El malestar ocurre frecuentemente?",
        "¿Aparecen los síntomas más de una vez al mes?",
        "¿Esto ocurre de forma constante?",
        "¿Tiene síntomas diarios?",
        "¿Es algo que ocurre semanalmente?",
        "¿El dolor es ocasional o frecuente?",
        "¿Los síntomas son esporádicos o regulares?",
        "¿Esto ocurre una vez por día o menos?",
        "¿Suele presentarse cada semana?",
        "¿Con qué regularidad siente esto?",
        "¿Experimenta el dolor de manera repetitiva?",
        "¿Es una molestia que viene y va?",
        "¿Se repite a menudo?",
        "¿Cuántas veces al mes lo siente?",
        "¿Esto pasa con frecuencia?",
        "¿El dolor ocurre cada cierto tiempo?",
        "¿Vuelve el malestar varias veces?",
        "¿Es una situación recurrente?",
        "¿Esto le sucede constantemente?",
        "¿Padece esto más de una vez por semana?",
        "¿Es común que aparezcan estos síntomas?",
        "¿Ocurre en ciertos días del mes?",
        "¿Esto pasa habitualmente?",
        "¿Es un problema que se presenta seguido?",
        "¿El dolor aparece a diario?",
        "¿Es una molestia constante?",
        "¿El síntoma se presenta sin falta cada semana?",
        "¿Cada cuánto nota el malestar?",
        "¿Esto le sucede cada dos días?",
        "¿Con qué periodicidad aparece el dolor?",
        "¿Es frecuente esta condición?",
        "¿La molestia ocurre con regularidad?",
        "¿Esto se manifiesta muchas veces?",
        "¿Con qué continuidad le sucede?",
        "¿Se le repite el síntoma durante la semana?",
        "¿Le ha pasado muchas veces últimamente?",
        "¿Los episodios son continuos?",
        "¿Esto sucede un par de veces a la semana?",
        "¿Esto ha sido muy seguido últimamente?",
        "¿Ha notado una frecuencia alta de episodios?",
        "¿Esto le ocurre de forma muy seguida?",
        "¿Le pasa varias veces por mes?",
        "¿Esto le sucede constantemente desde hace tiempo?",
        "¿Esto se ha vuelto común?",
        "¿Tiene episodios reiterativos?",
        "¿Lo siente muchas veces al mes?",
        "¿Este síntoma es persistente?"
    ],
    "intensidad": [
        "¿Qué tan fuerte es el dolor que siente?",
        "¿Puede calificar el dolor del 1 al 10?",
        "¿Diría que el dolor es leve, moderado o fuerte?",
        "¿Es un dolor soportable o insoportable?",
        "¿Qué nivel de intensidad tiene el dolor?",
        "¿El dolor es agudo o más bien leve?",
        "¿Se siente una presión intensa o ligera?",
        "¿El malestar es intenso o tolerable?",
        "¿Es un dolor constante y fuerte?",
        "¿Cómo describiría la severidad del dolor?",
        "¿El dolor le impide hacer sus actividades?",
        "¿El nivel del dolor cambia o se mantiene fuerte?",
        "¿Qué grado de intensidad siente cuando duele?",
        "¿El dolor es lo suficientemente fuerte como para detenerse?",
        "¿Es una molestia apenas perceptible o muy clara?",
        "¿Podría comparar el dolor con algo conocido en intensidad?",
        "¿Es un dolor incapacitante?",
        "¿Cuánto le duele exactamente?",
        "¿El dolor lo obliga a acostarse o detenerse?",
        "¿Es un malestar leve que puede ignorar?",
        "¿Le hace llorar o le quita el aliento?",
        "¿Es un dolor punzante que no lo deja en paz?",
        "¿Se siente presionado por el dolor?",
        "¿Es tan fuerte que no puede concentrarse?",
        "¿Lo despierta el dolor durante la noche?",
        "¿Podría seguir con su día normal con este nivel de dolor?",
        "¿Necesita medicación para calmar el dolor?",
        "¿El dolor lo deja sin energía o fuerzas?",
        "¿Siente que el dolor empeora a lo largo del día?",
        "¿Es un dolor intermitente o siempre intenso?",
        "¿El dolor aparece con una intensidad inesperada?",
        "¿Se siente desbordado por la intensidad del dolor?",
        "¿Es un dolor que se extiende con fuerza?",
        "¿Lo obliga a detener cualquier tarea que realice?",
        "¿El malestar es tan fuerte que no puede hablar bien?",
        "¿Le genera náuseas por la intensidad?",
        "¿Ha sentido antes un dolor tan intenso?",
        "¿Le genera angustia el nivel del dolor?",
        "¿El dolor lo hace sudar o temblar?",
        "¿Se siente al borde del colapso por el dolor?",
        "¿Puede caminar o moverse con ese dolor?",
        "¿El dolor lo hace llorar o gritar?",
        "¿Es similar a una crisis dolorosa?",
        "¿Podría soportar este dolor por mucho tiempo?",
        "¿Necesita sentarse o recostarse por el dolor?",
        "¿El dolor le nubla la vista por la intensidad?",
        "¿Siente que el dolor domina todo su cuerpo?",
        "¿Es tan intenso que necesita ayuda inmediata?",
        "¿Es el dolor lo peor que ha sentido?",
        "¿El nivel de dolor es similar al de una cirugía?"
    ],
    "localizacion": [
        "¿Dónde siente exactamente el dolor?",
        "¿En qué parte del cuerpo se localiza el malestar?",
        "¿Podría señalar dónde le duele?",
        "¿El dolor está ubicado en un solo lugar?",
        "¿Se presenta en el lado derecho o izquierdo?",
        "¿Siente el dolor en la cabeza, abdomen o espalda?",
        "¿Dónde comienza el dolor?",
        "¿El malestar está en las extremidades?",
        "¿Le duele el pecho o el estómago?",
        "¿Siente dolor en los músculos o las articulaciones?",
        "¿Dónde nota el punto más intenso del dolor?",
        "¿Está focalizado en una zona específica?",
        "¿El dolor aparece en más de una región?",
        "¿Tiene dolor en la parte superior del cuerpo?",
        "¿Está en la pierna, brazo, cuello u otra zona?",
        "¿Siente una presión localizada?",
        "¿Puede identificar la zona exacta del dolor?",
        "¿Es un dolor abdominal, torácico o cefálico?",
        "¿Lo siente en la parte trasera o delantera del cuerpo?",
        "¿Se presenta más en la parte interna o externa?",
        "¿Afecta una sola parte del cuerpo o varias?",
        "¿Siente el dolor cerca de los órganos internos?",
        "¿El dolor se siente superficial o profundo?",
        "¿Está presente en la parte baja de la espalda?",
        "¿Es un dolor central o lateralizado?",
        "¿Tiene molestias en la nuca o las sienes?",
        "¿Se sitúa en los costados o el centro del abdomen?",
        "¿El malestar se presenta en la pelvis?",
        "¿Está localizado en la región lumbar?",
        "¿Siente dolor en las manos o en los pies?",
        "¿Está en la zona ocular, nasal o auditiva?",
        "¿Le duele una articulación específica?",
        "¿El dolor está en el área torácica?",
        "¿Es un dolor que se localiza en el rostro?",
        "¿Le duele el cuero cabelludo?",
        "¿Siente el dolor en la columna vertebral?",
        "¿En qué área corporal comenzó el síntoma?",
        "¿Dónde se manifiesta más el malestar?",
        "¿Le molesta una zona concreta?",
        "¿Siente la molestia en la parte interna del muslo?",
        "¿La molestia se concentra en un solo punto?",
        "¿El dolor está confinado a una zona pequeña?",
        "¿En qué zona corporal nota el dolor con más fuerza?",
        "¿Se ubica el dolor en los glúteos?",
        "¿El malestar se extiende desde un punto específico?",
        "¿La zona del dolor cambia o es fija?",
        "¿Siente que una zona está más afectada que otras?",
        "¿Hay un lugar que le duela al presionarlo?",
        "¿El dolor se limita a una parte específica del cuerpo?",
        "¿Se encuentra el dolor cerca de la piel o más profundo?"
    ],
    "agravamiento": [
        "¿Hay algo que empeore el dolor?",
        "¿El dolor se agrava con el movimiento?",
        "¿Notas si algo lo intensifica?",
        "¿Empeora cuando haces ejercicio?",
        "¿Se vuelve más fuerte al caminar?",
        "¿La luz brillante lo agrava?",
        "¿El ruido fuerte hace que aumente?",
        "¿El estrés hace que se intensifique?",
        "¿Sientes que la comida lo empeora?",
        "¿Los cambios de clima afectan el dolor?",
        "¿Aumenta cuando no duerme bien?",
        "¿Se agrava con ciertos olores?",
        "¿Alguna actividad lo vuelve más severo?",
        "¿Notas que el dolor crece al agacharte?",
        "¿Sentarse lo hace peor?",
        "¿Al estar de pie por mucho tiempo se agrava?",
        "¿El dolor se intensifica al cargar peso?",
        "¿Las emociones fuertes aumentan el dolor?",
        "¿Cuando está en tensión el dolor crece?",
        "¿El dolor empeora si no toma medicamentos?",
        "¿Comer ciertos alimentos lo hace más fuerte?",
        "¿El café o el alcohol afectan el malestar?",
        "¿El dolor crece con el esfuerzo físico?",
        "¿Le afecta más en lugares con ruido?",
        "¿El calor o el frío intensifican el dolor?",
        "¿Cambiar de postura lo empeora?",
        "¿Los movimientos bruscos aumentan el dolor?",
        "¿Toser o estornudar agravan el malestar?",
        "¿El dolor empeora si se mueve rápido?",
        "¿Al subir escaleras lo siente más fuerte?",
        "¿Después de comer lo siente más?",
        "¿El dolor aparece tras realizar alguna tarea?",
        "¿Con ciertos movimientos siente más dolor?",
        "¿La ansiedad o preocupación lo agravan?",
        "¿Estar en lugares cerrados afecta el dolor?",
        "¿Con el paso de las horas aumenta el dolor?",
        "¿El dolor se hace peor por la tarde o noche?",
        "¿Cuando se levanta rápido duele más?",
        "¿Al girar el cuerpo el dolor aumenta?",
        "¿La menstruación influye en el dolor?",
        "¿Hay posturas que empeoran el síntoma?",
        "¿Lo siente más cuando está bajo presión?",
        "¿La falta de descanso lo hace más agudo?",
        "¿Los esfuerzos repetitivos lo intensifican?",
        "¿Hay sonidos que provocan más dolor?",
        "¿Movimientos repetidos agravan la molestia?",
        "¿Se intensifica si no descansa bien?",
        "¿Hay situaciones que agravan el malestar?",
        "¿Al estar en lugares calurosos lo nota más?",
        "¿Qué cosas sabe que empeoran el dolor?"
    ],
    "inicio": [
        "¿Desde cuándo comenzó el dolor?",
        "¿Cuándo notó por primera vez los síntomas?",
        "¿Recuerda el momento en que empezó el malestar?",
        "¿El dolor inició hace mucho o poco tiempo?",
        "¿Cuánto tiempo ha pasado desde que empezó?",
        "¿Desde qué día tiene esta molestia?",
        "¿Cuándo aparecieron los síntomas por primera vez?",
        "¿Hace cuánto que tiene este problema?",
        "¿Puede decirme cuándo comenzó exactamente?",
        "¿Fue repentino o progresivo el inicio del dolor?",
        "¿El malestar apareció hace unos días o semanas?",
        "¿Esto empezó recientemente?",
        "¿Desde hace cuánto nota los síntomas?",
        "¿Desde hace cuántas horas lo siente?",
        "¿El dolor empezó esta semana?",
        "¿Fue un inicio súbito o gradual?",
        "¿Cuándo comenzó este episodio?",
        "¿Este dolor lo tiene desde ayer o antes?",
        "¿Cuánto tiempo lleva con esta dolencia?",
        "¿Esto inició hace más de una semana?",
        "¿Puede identificar cuándo fue el inicio exacto?",
        "¿Sabe si empezó tras algún evento?",
        "¿Se presentó de forma inesperada?",
        "¿Cuándo notó que algo andaba mal?",
        "¿Sabe qué día comenzaron los síntomas?",
        "¿Hace cuánto se siente así?",
        "¿Puede estimar desde cuándo tiene este malestar?",
        "¿Recuerda si fue reciente o de hace meses?",
        "¿Hace días que lo padece?",
        "¿Desde cuándo tiene molestias similares?",
        "¿Esto comenzó de forma lenta o abrupta?",
        "¿El primer síntoma fue hace cuánto?",
        "¿Empezó hace unas horas o días?",
        "¿Este dolor lo acompaña desde cuándo?",
        "¿Notó los síntomas desde hace tiempo?",
        "¿Hace cuánto ocurrió el primer episodio?",
        "¿Desde qué fecha tiene el problema?",
        "¿Puede señalar el día del inicio?",
        "¿El inicio fue repentino o paulatino?",
        "¿Cuándo fue la primera vez que lo notó?",
        "¿Desde hace cuánto lo experimenta?",
        "¿Lo sufre desde algún momento específico?",
        "¿Desde qué evento cree que comenzó?",
        "¿Desde cuándo siente que algo no está bien?",
        "¿Hace cuánto empezó a sentir molestias?",
        "¿Este malestar comenzó esta semana?",
        "¿El dolor surgió de la nada o fue aumentando?",
        "¿Esto viene ocurriendo desde hace cuánto?",
        "¿Tiene una idea del momento en que comenzó?",
        "¿Desde qué día exacto tiene el síntoma?"
    ],
    "irradiacion": [
        "¿El dolor se expande hacia otras zonas del cuerpo?",
        "¿Siente que el dolor se irradia?",
        "¿El dolor se mueve o permanece en un solo lugar?",
        "¿Se extiende el dolor a otras partes?",
        "¿El malestar recorre otras regiones de su cuerpo?",
        "¿El dolor se propaga desde donde empezó?",
        "¿Lo siente en una zona y luego en otra?",
        "¿Siente que el dolor viaja por el cuerpo?",
        "¿La molestia aparece también en otras áreas?",
        "¿El dolor afecta también a los brazos o piernas?",
        "¿El dolor se traslada a otras partes del cuerpo?",
        "¿Empieza en un lugar y se expande?",
        "¿La sensación de dolor cambia de ubicación?",
        "¿El malestar se irradia a otras áreas?",
        "¿Siente el dolor en varias partes a la vez?",
        "¿El dolor se manifiesta en otra zona también?",
        "¿Nota que se irradia hacia el cuello o espalda?",
        "¿El dolor sube o baja a lo largo del cuerpo?",
        "¿El dolor se refleja en otras áreas?",
        "¿Se presenta en un sitio y luego en otro?",
        "¿Hay una zona donde comienza y otra donde termina?",
        "¿El dolor sigue un trayecto corporal?",
        "¿Se irradia hacia alguna extremidad?",
        "¿Siente que el dolor corre por el cuerpo?",
        "¿Se desplaza la molestia con el tiempo?",
        "¿Se expande desde el centro hacia afuera?",
        "¿A veces cambia de zona?",
        "¿El dolor afecta también otras áreas contiguas?",
        "¿Siente que se mueve a lo largo del día?",
        "¿Afecta también zonas alejadas del punto inicial?",
        "¿Se presenta en un lado y luego en otro?",
        "¿Lo siente en diferentes niveles del cuerpo?",
        "¿El dolor sube desde el abdomen al pecho?",
        "¿Se propaga por la espalda?",
        "¿Irradia hacia la mandíbula u oído?",
        "¿La molestia va desde un punto a varios más?",
        "¿Se nota el dolor en otras regiones también?",
        "¿Se ramifica la sensación del dolor?",
        "¿Abarca más que un solo sitio?",
        "¿Siente que corre hacia el brazo o pierna?",
        "¿Se expande por el torso?",
        "¿Siente dolor reflejado en otra parte?",
        "¿Irradia a zonas alejadas del lugar de inicio?",
        "¿Siente el mismo dolor en zonas simétricas?",
        "¿Se repite el malestar en áreas distintas?",
        "¿Es un dolor que se distribuye por el cuerpo?",
        "¿Aparece en varios puntos relacionados?",
        "¿Siente que el dolor fluye o se dispersa?",
        "¿El dolor toma un camino por el cuerpo?",
        "¿Irradia hacia la espalda baja o los hombros?"
    ],
    "descripcion_dolor": [
        "¿Cómo describiría el tipo de dolor que siente?",
        "¿El dolor es punzante, ardoroso o sordo?",
        "¿Es una presión, un pinchazo o una quemazón?",
        "¿Siente que le pulsa o le aprieta?",
        "¿El dolor es constante o intermitente?",
        "¿Tiene forma de latido o es más bien una presión?",
        "¿Es un dolor agudo o más bien suave?",
        "¿La molestia es como un choque eléctrico?",
        "¿Le arde o quema la zona afectada?",
        "¿Lo siente como una punzada o como tensión?",
        "¿Es una sensación que va y viene?",
        "¿El dolor es como un calambre?",
        "¿Se siente como si lo apretaran fuerte?",
        "¿Es más bien un dolor sordo o vibrante?",
        "¿Siente un golpe interno o una presión localizada?",
        "¿El dolor se parece a un tirón muscular?",
        "¿Es como si algo lo quemara por dentro?",
        "¿Siente presión, hormigueo o dolor punzante?",
        "¿Lo siente como si algo le estallara dentro?",
        "¿La molestia es fuerte como un martilleo?",
        "¿Podría compararlo con un pinchazo de aguja?",
        "¿Es como si lo estuvieran apretando con fuerza?",
        "¿Tiene una sensación opresiva o expansiva?",
        "¿Es un dolor que pica, arde o quema?",
        "¿Le duele como si se estirara algo por dentro?",
        "¿Es un dolor seco o húmedo, profundo o superficial?",
        "¿Lo siente como una corriente eléctrica?",
        "¿Es un dolor que da puntadas o como cuchilladas?",
        "¿La sensación es más como presión o como ardor?",
        "¿Es como si le clavaran algo?",
        "¿Es constante o aparece por momentos?",
        "¿Siente espasmos dolorosos?",
        "¿Es como si se inflamaran los tejidos?",
        "¿Siente rigidez junto con dolor?",
        "¿El dolor se intensifica con el movimiento o al respirar?",
        "¿Es una molestia que impide pensar claramente?",
        "¿Es como una presión desde adentro hacia afuera?",
        "¿Siente como si se expandiera en oleadas?",
        "¿El dolor tiene forma de palpitación?",
        "¿Lo compararía con una presión creciente?",
        "¿Siente que el dolor gira o vibra?",
        "¿Es una molestia parecida a un ardor solar?",
        "¿Tiene una sensación de opresión en la zona?",
        "¿Es un dolor parecido al de una migraña fuerte?",
        "¿La molestia es sutil o bien definida?",
        "¿Siente que lo comprimen o le halan algo dentro?",
        "¿Lo describiría como una corriente pulsante?",
        "¿El dolor lo siente como algo expansivo?",
        "¿Es como si le punzaran en intervalos?",
        "¿Tiene forma de espasmo o descarga?"
    ],
    "sintomas": [
        "¿Tiene algún otro síntoma además del dolor?",
        "¿Presenta fiebre, náuseas u otra molestia?",
        "¿Experimenta escalofríos o sudoración?",
        "¿Ha notado mareos o vómito?",
        "¿Acompaña al dolor algún otro malestar?",
        "¿Siente debilidad o fatiga?",
        "¿Tiene visión borrosa o dificultad para concentrarse?",
        "¿Ha perdido el apetito últimamente?",
        "¿Siente molestias estomacales además del dolor?",
        "¿Tiene algún síntoma adicional?",
        "¿Se le dificulta respirar?",
        "¿Presenta zumbidos en los oídos?",
        "¿Siente hormigueo o adormecimiento?",
        "¿Ha tenido desmayos o episodios de confusión?",
        "¿Ha notado palpitaciones o taquicardias?",
        "¿Siente rigidez o tensión muscular?",
        "¿Tiene temblores o movimientos involuntarios?",
        "¿Sufre cambios de temperatura corporal?",
        "¿Siente presión en el pecho?",
        "¿Ha notado sudoraciones nocturnas?",
        "¿Tiene sensibilidad a la luz o al sonido?",
        "¿Ha tenido dificultad para dormir?",
        "¿Ha perdido peso sin razón aparente?",
        "¿Siente náuseas constantes?",
        "¿Tiene sensación de malestar general?",
        "¿Ha tenido alteraciones en el ritmo cardíaco?",
        "¿Nota entumecimiento en alguna parte del cuerpo?",
        "¿Siente inflamación o hinchazón?",
        "¿Tiene dificultad para hablar o moverse?",
        "¿Siente que pierde el equilibrio?",
        "¿Ha notado cambios en la presión arterial?",
        "¿Ha tenido fiebre en los últimos días?",
        "¿Siente que le falta energía?",
        "¿Tiene molestias al orinar?",
        "¿Experimenta dolor en más de una parte del cuerpo?",
        "¿Se le dificulta comer o tragar?",
        "¿Tiene visión doble o borrosa?",
        "¿Ha sentido sensación de desmayo?",
        "¿Siente frío constante sin causa evidente?",
        "¿Tiene tos persistente u otro síntoma respiratorio?",
        "¿Sufre de cambios de humor inusuales?",
        "¿Nota su pulso acelerado sin motivo?",
        "¿Siente presión en la cabeza?",
        "¿Tiene problemas para mantenerse en pie?",
        "¿Ha tenido cambios en su apetito?",
        "¿Siente que su cuerpo no responde como antes?",
        "¿Tiene dificultad para concentrarse?",
        "¿Siente tensión en el cuello o espalda?",
        "¿Percibe debilidad en alguna extremidad?",
        "¿Tiene sensación de ardor o picor sin lesión visible?"
    ],
    "medicamento": [
        "¿Ha tomado algún medicamento para aliviar el dolor?",
        "¿Qué pastillas ha usado recientemente?",
        "¿Está usando algún fármaco para tratar los síntomas?",
        "¿Se automedicó antes de venir a consulta?",
        "¿Está en algún tratamiento actualmente?",
        "¿Qué remedios ha probado hasta ahora?",
        "¿Tomó algo por su cuenta para el dolor?",
        "¿Qué tipo de analgésico ha ingerido?",
        "¿Ha usado paracetamol, ibuprofeno u otro medicamento?",
        "¿Le recetaron algo previamente?",
        "¿Sigue algún tratamiento médico por esta razón?",
        "¿Usó alguna medicina sin receta?",
        "¿Tomó algún antiinflamatorio últimamente?",
        "¿Inició algún tratamiento en casa?",
        "¿Ha ingerido algo para calmar los síntomas?",
        "¿Ha usado remedios naturales o caseros?",
        "¿Recibió medicamentos en una consulta previa?",
        "¿Está tomando algún medicamento ahora mismo?",
        "¿Recibió alguna indicación farmacológica reciente?",
        "¿Está tomando algo que le recomendaron familiares o amigos?",
        "¿Consiguió alguna medicina en la farmacia por su cuenta?",
        "¿Le recetaron algo en otra clínica?",
        "¿Está repitiendo alguna receta anterior?",
        "¿Tomó medicina de la última vez que sintió lo mismo?",
        "¿Pidió algo en la farmacia para esto?",
        "¿Ha tomado antibióticos por su cuenta?",
        "¿Tiene alguna receta que siga actualmente?",
        "¿Utilizó alguna pomada o parche?",
        "¿Usó gotas, jarabe u otra presentación?",
        "¿Aplicó algo en la zona afectada?",
        "¿Usa pastillas para el dolor frecuentemente?",
        "¿Tomó algo esta mañana o ayer?",
        "¿Se le indicó algún tratamiento y lo está siguiendo?",
        "¿Inició por su cuenta algún plan de medicación?",
        "¿Lleva más de un día tomando medicina?",
        "¿Usó medicamentos viejos que tenía en casa?",
        "¿Probó tratamientos alternativos o homeopatía?",
        "¿Está bajo supervisión médica con medicamentos?",
        "¿Usó medicamentos de otro padecimiento para esto?",
        "¿Tomó medicina que tenía guardada?",
        "¿Sigue usando el medicamento anterior?",
        "¿Probó algún calmante natural?",
        "¿Sigue tomando algo aunque ya se sienta mejor?",
        "¿Ha tomado analgésicos sin supervisión médica?",
        "¿Sabe el nombre del medicamento que usó?",
        "¿Ha tenido efectos con algún medicamento reciente?",
        "¿Le hizo efecto la medicina que tomó?",
        "¿Tomó más de una dosis?",
        "¿Tomó algo y no le funcionó?",
        "¿Empeoró después de usar alguna medicina?"
    ],
    "diagnostico": [
        "El diagnóstico más probable es migraña.",
        "Parece que está sufriendo de cefalea tensional.",
        "Todo indica que podría ser una neuralgia.",
        "Es posible que tenga una migraña con aura.",
        "Los síntomas son compatibles con cefalea crónica.",
        "Parece tratarse de una jaqueca.",
        "El cuadro clínico sugiere una cefalea mixta.",
        "Este caso apunta a una migraña episódica.",
        "Podría estar presentando dolor de cabeza tensional.",
        "Este patrón se asocia con cefalea por estrés.",
        "La enfermedad parece ser migraña sin aura.",
        "Se observa una presentación típica de jaqueca común.",
        "Se trata probablemente de una cefalea de tipo tensional.",
        "El perfil del dolor coincide con migraña menstrual.",
        "El dolor se asemeja al de una cefalea cervicogénica.",
        "Parece tratarse de una cefalea inducida por medicamentos.",
        "Es un caso característico de dolor tensional crónico.",
        "Se sospecha una neuralgia del trigémino.",
        "Los hallazgos clínicos sugieren cefalea en racimos.",
        "Esto podría ser un episodio de cefalea por resaca.",
        "El dolor cumple criterios de migraña leve a moderada.",
        "Todo parece indicar que es una migraña recurrente.",
        "Tiene signos clásicos de jaqueca con fotofobia.",
        "Se ajusta al diagnóstico de cefalea primaria.",
        "Lo que describe suena como una cefalea secundaria.",
        "Es muy probable que se trate de una cefalea tensional leve.",
        "Podría diagnosticarse como migraña sin complicaciones.",
        "Todo indica que sufre cefalea relacionada con el sueño.",
        "La evaluación clínica sugiere una jaqueca típica.",
        "Este dolor es compatible con cefalea relacionada al estrés.",
        "Podría tratarse de una cefalea por alteración hormonal.",
        "Presenta un cuadro clínico de migraña crónica.",
        "El patrón de dolor apunta a cefalea hipnica.",
        "Este tipo de molestia es típico de cefalea tensional aguda.",
        "Podríamos estar ante una neuralgia postherpética.",
        "Este caso es representativo de cefalea en racimo.",
        "Parece tener una cefalea por privación de cafeína.",
        "La descripción concuerda con migraña vestibular.",
        "Es probable que tenga una cefalea postraumática.",
        "Se trata de un tipo de cefalea episódica frecuente.",
        "Corresponde a una cefalea de origen vascular.",
        "El dolor es característico de cefalea frontal.",
        "La sintomatología se relaciona con migraña digestiva.",
        "El perfil clínico indica una cefalea aguda intermitente.",
        "Sufre de una cefalea con componente visual significativo.",
        "Los síntomas sugieren una cefalea climatérica.",
        "Todo apunta a una cefalea tensional multifactorial.",
        "Se identifica una migraña de tipo familiar.",
        "Su condición parece ser migraña inducida por alimentos.",
        "Podría estar padeciendo cefalea del esfuerzo."
    ]
}

# Preparar datos
frases = []
etiquetas = []
for categoria, ejemplos in frases_por_categoria.items():
    frases.extend([preprocesar_texto(f) for f in ejemplos])
    etiquetas.extend([categoria] * len(ejemplos))

# Dividir datos
X_train, X_test, y_train, y_test = train_test_split(frases, etiquetas, test_size=0.2, random_state=42)

# Entrenar modelo
modelo = make_pipeline(TfidfVectorizer(), LogisticRegression(max_iter=1000))
modelo.fit(X_train, y_train)

# Evaluar modelo
y_pred = modelo.predict(X_test)
print(classification_report(y_test, y_pred))

# Guardar modelo
joblib.dump(modelo, "modelo_entrenado.pkl")
print("Modelo entrenado y guardado con éxito.")
